services:
  pyspark:
    build: .
    container_name: pyspark-dev
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - SPARK_MASTER=spark://spark-master:7077
